name: bitchat
options:
  bundleIdPrefix: com.cypherbase.bitchat
  deploymentTarget:
    iOS: 17.6
    macOS: 13.0
  createIntermediateGroups: true
  
settings:
  MARKETING_VERSION: 1.0.0
  CURRENT_PROJECT_VERSION: 1

packages:
  CashuSwift:
    url: https://github.com/zeugmaster/CashuSwift
    branch: main
  
targets:
  bitchat_iOS:
    type: application
    platform: iOS
    sources: 
      - path: bitchat
        excludes:
          - "Info-*.plist"
    resources:
      - bitchat/Assets.xcassets
      - bitchat/LaunchScreen.storyboard
    info:
      path: bitchat/Info-iOS.plist
      properties:
        CFBundleDisplayName: bitchat
        CFBundleShortVersionString: $(MARKETING_VERSION)
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
        NSBluetoothAlwaysUsageDescription: bitchat uses Bluetooth to create a secure mesh network for chatting with nearby users.
        NSBluetoothPeripheralUsageDescription: bitchat uses Bluetooth to discover and connect with other bitchat users nearby.
        UIBackgroundModes:
          - bluetooth-central
          - bluetooth-peripheral
        UILaunchStoryboardName: LaunchScreen
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UIRequiresFullScreen: false
        CFBundleURLTypes:
          - CFBundleURLSchemes:
              - bitchat
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.cypherbase.bitchat
      PRODUCT_NAME: bitchat
      INFOPLIST_FILE: bitchat/Info-iOS.plist
      ENABLE_PREVIEWS: YES
      SWIFT_VERSION: 5.0
      IPHONEOS_DEPLOYMENT_TARGET: 17.6
      SUPPORTS_MAC_DESIGNED_FOR_IPHONE_IPAD: YES
      CODE_SIGN_STYLE: Automatic
      CODE_SIGNING_REQUIRED: YES
      CODE_SIGNING_ALLOWED: YES
      DEVELOPMENT_TEAM: W285RX5S82
      ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
      ASSETCATALOG_COMPILER_INCLUDE_ALL_APPICON_ASSETS: YES
      CODE_SIGN_ENTITLEMENTS: bitchat/bitchat.entitlements
    dependencies:
      - package: CashuSwift
      
  bitchat_macOS:
    type: application
    platform: macOS
    sources: 
      - path: bitchat
        excludes:
          - "Info-*.plist"
    resources:
      - bitchat/Assets.xcassets
    info:
      path: bitchat/Info-macOS.plist
      properties:
        CFBundleDisplayName: bitchat
        CFBundleShortVersionString: $(MARKETING_VERSION)
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
        NSBluetoothAlwaysUsageDescription: bitchat uses Bluetooth to create a secure mesh network for chatting with nearby users.
        NSBluetoothPeripheralUsageDescription: bitchat uses Bluetooth to discover and connect with other bitchat users nearby.
        CFBundleURLTypes:
          - CFBundleURLSchemes:
              - bitchat
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.cypherbase.bitchat
      PRODUCT_NAME: bitchat
      INFOPLIST_FILE: bitchat/Info-macOS.plist
      ENABLE_PREVIEWS: YES
      SWIFT_VERSION: 5.0
      MACOSX_DEPLOYMENT_TARGET: 13.0
      CODE_SIGN_STYLE: Automatic
      CODE_SIGNING_REQUIRED: YES
      CODE_SIGNING_ALLOWED: YES
      DEVELOPMENT_TEAM: W285RX5S82
      ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
      ASSETCATALOG_COMPILER_INCLUDE_ALL_APPICON_ASSETS: YES
      CODE_SIGN_ENTITLEMENTS: bitchat/bitchat-macOS.entitlements
    dependencies:
      - package: CashuSwift
      
  bitchatShareExtension:
    type: app-extension
    platform: iOS
    sources: 
      - bitchatShareExtension
    info:
      path: bitchatShareExtension/Info.plist
      properties:
        NSExtension:
          NSExtensionPrincipalClass: ShareViewController
          NSExtensionPointIdentifier: com.apple.share-services
          NSExtensionAttributes:
            NSExtensionActivationRule:
              NSExtensionActivationSupportsWebURLWithMaxCount: 1
              NSExtensionActivationSupportsImageWithMaxCount: 1
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.cypherbase.bitchat.ShareExtension
      INFOPLIST_FILE: bitchatShareExtension/Info.plist
      SWIFT_VERSION: 5.0
      IPHONEOS_DEPLOYMENT_TARGET: 17.6
      CODE_SIGN_STYLE: Automatic
      CODE_SIGNING_REQUIRED: YES
      CODE_SIGNING_ALLOWED: YES
      DEVELOPMENT_TEAM: W285RX5S82
      CODE_SIGN_ENTITLEMENTS: bitchatShareExtension/bitchatShareExtension.entitlements
      CODE_SIGN_ALLOW_ENTITLEMENTS_MODIFICATION: YES

  bitchatTests_iOS:
    type: bundle.unit-test
    platform: iOS
    sources: 
      - bitchatTests
    dependencies:
      - target: bitchat_iOS
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.cypherbase.bitchat.tests
      INFOPLIST_FILE: bitchatTests/Info.plist
      SWIFT_VERSION: 5.0
      IPHONEOS_DEPLOYMENT_TARGET: 17.6
      TARGETED_DEVICE_FAMILY: 1,2
      CODE_SIGN_STYLE: Automatic
      CODE_SIGNING_REQUIRED: YES
      CODE_SIGNING_ALLOWED: YES
      DEVELOPMENT_TEAM: W285RX5S82
      
  bitchatTests_macOS:
    type: bundle.unit-test
    platform: macOS
    sources: 
      - bitchatTests
    dependencies:
      - target: bitchat_macOS
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.cypherbase.bitchat.tests
      INFOPLIST_FILE: bitchatTests/Info.plist
      SWIFT_VERSION: 5.0
      MACOSX_DEPLOYMENT_TARGET: 13.0
      CODE_SIGN_STYLE: Automatic
      CODE_SIGNING_REQUIRED: YES
      CODE_SIGNING_ALLOWED: YES
      DEVELOPMENT_TEAM: W285RX5S82

schemes:
  bitchat (iOS):
    build:
      targets:
        bitchat_iOS: all
        bitchatShareExtension: all
        bitchatTests_iOS: [test]
    run:
      config: Debug
    test:
      config: Debug
      targets:
        - bitchatTests_iOS
    
  bitchat (macOS):
    build:
      targets:
        bitchat_macOS: all
        bitchatTests_macOS: [test]
    run:
      config: Debug
    test:
      config: Debug
      targets:
        - bitchatTests_macOS
